version: '1.0'
name: pr-pipeline
displayName: 部署gh-pages
triggers:
  trigger: manual
stages:
  - name: compile
    displayName: 编译
    strategy: naturally
    trigger: auto
    steps:
      - step: build@nodejs
        name: build_nodejs
        displayName: Nodejs 构建
        nodeVersion: 14.16.0
        commands:
          - npm install && rm -rf ./docs/.vuepress/dist && npm run docs:build
        artifacts:
          - name: BUILD_ARTIFACT
            path:
              - ./docs/.vuepress/dist
        strategy: {}
      - step: publish@general_artifacts
        name: publish_general_artifacts
        displayName: 上传制品
        dependArtifact: BUILD_ARTIFACT
        artifactName: output
        strategy: {}
        dependsOn: build_nodejs
